image: docker:latest
variables:
  APPLICATION_URL: "https://${APPLICATION_HOST}"
  DOCKER_TLS_CERTDIR: "/certs"
  BUILDER_IMAGE_REF: "${CI_REGISTRY_IMAGE}/builder:${CI_COMMIT_SHORT_SHA}"
  BUILDER_IMAGE_TAG: "${CI_REGISTRY_IMAGE}/builder:${CI_COMMIT_REF_SLUG}"
  DOCKER_IMAGE_REF: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  DOCKER_IMAGE_TAG: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
  DOCKER_IMAGE_LATEST: "${CI_REGISTRY_IMAGE}:latest"

services:
  - docker:dind

stages:
  - build
  - release

before_script:
  - docker login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"

build:
  stage: build
  script:
    - |-
      if docker pull "${BUILDER_IMAGE_REF}" &> /dev/null
      then
        docker tag "${BUILDER_IMAGE_REF}" "${BUILDER_IMAGE_TAG}"
      else
        docker pull "${BUILDER_IMAGE_TAG}" &> /dev/null || true
      fi
    - docker build --target "builder"
      --cache-from "${BUILDER_IMAGE_TAG}"
      --tag "${BUILDER_IMAGE_REF}"
      --tag "${BUILDER_IMAGE_TAG}"
      --build-arg VITE_BACKEND_URL="${APPLICATION_URL}"
      .

    - docker push "${BUILDER_IMAGE_REF}"
    - docker tag "${BUILDER_IMAGE_REF}" "${BUILDER_IMAGE_TAG}"
    - docker push "${BUILDER_IMAGE_TAG}"

    - |-
      if docker pull "${DOCKER_IMAGE_REF}" &> /dev/null
      then
        docker tag "${DOCKER_IMAGE_REF}" "${DOCKER_IMAGE_TAG}"
      else
        docker pull "${DOCKER_IMAGE_TAG}" &> /dev/null || true
      fi
    - docker build
      --cache-from "${BUILDER_IMAGE_TAG}"
      --cache-from "${DOCKER_IMAGE_TAG}"
      --tag "${DOCKER_IMAGE_REF}"
      --tag "${DOCKER_IMAGE_TAG}"
      --build-arg VITE_BACKEND_URL="${APPLICATION_URL}"
      --build-arg AUTHOR="${GITLAB_USER_NAME}"
      --build-arg COMMIT_SHA="${CI_COMMIT_SHA}"
      --build-arg COMMIT_REF="${CI_COMMIT_REF}"
      --build-arg CREATE_DATE="${CI_PIPELINE_CREATED_AT}"
      .

    - docker push "${DOCKER_IMAGE_REF}"
    - docker push "${DOCKER_IMAGE_TAG}"

  rules:
    - exists:
      - Dockerfile
    - if: '"${CI_COMMIT_BRANCH}" =~ /^(master|production)$/'
      when: on_success
    - if: '"${CI_COMMIT_BRANCH}" =~ /^feature\//'
      when: manual
    - when: never

release:
  stage: release
  script:
    - docker pull "${DOCKER_IMAGE_REF}"
    - docker tag "${DOCKER_IMAGE_REF}" "${DOCKER_IMAGE_LATEST}"
    - docker push "${DOCKER_IMAGE_LATEST}"

  only:
    - production
