version: "3.9"
services:
  nginx:
    build: .
    image: do-you-dare/frontend:latest
    env_file:
      - .env

    labels:
      traefik.enable: true
      traefik.http.routers.do-you-dare.entrypoints: websecure
      traefik.http.routers.do-you-dare.rule: Host(`${HOSTNAME}`)
      traefik.http.routers.do-you-dare.tls: true
      traefik.http.routers.do-you-dare.tls.certresolver: letsencrypt
      traefik.http.services.do-you-dare.loadbalancer.server.port: 80

    networks:
      - default

    ports:
      - 80:80

networks:
  default:
