version: "3.9"
services:
  nginx:
    build:
      context: .
      args:
        - VITE_BACKEND_URL=http://localhost:8000

    image: do-you-dare/frontend:latest
    env_file:
      - .env

    labels:
      traefik.enable: true
      traefik.http.routers.do-you-dare_frontend.entrypoints: websecure
      traefik.http.routers.do-you-dare_frontend.rule: Host(`${HOSTNAME}`)
      traefik.http.routers.do-you-dare_frontend.tls: true
      traefik.http.routers.do-you-dare_frontend.tls.certresolver: letsencrypt
      traefik.http.services.do-you-dare_frontend.loadbalancer.server.port: 80

    networks:
      - default

    ports:
      - 8080:80

networks:
  default:
